# service-monitor
version: '2'
services:
    service-monitor:
        image: 192.168.200.56:8000/dist/service-monitor:v1.0.0
        restart: always
        container_name: service-monitor
        ports:
            - 2210:2210
            - 2211:8080
        environment:
          ZOOKEEPER_HOST: 192.168.200.56
          ZOOKEEPER_PORT: 2181
          DB_URL: jdbc:oracle:thin:@192.168.200.73:1521:orcl
          DB_USER_NAME: service_monitor
          DB_USER_PASSWORD: passw0rd
