# redis server
version: '2'
services:
    mysql:
        image: 192.168.200.56:8000/dist/mysql
        restart: always
        container_name: mydocker-mysql
        ports:
            - 13306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=passw0rd
          - MYSQL_ALLOW_EMPTY_PASSWORD=no
          - MYSQL_RANDOM_ROOT_PASSWORD=no
        volumes:
          - /data/mysql:/var/lib/mysql
          
