#pull down jdk-tomcat-8:v1.0.0 image
FROM 192.168.200.56:8000/dist/tomcat:8.5.15-jre8-alpine
MAINTAINER weifj

COPY ./dcm-service-biz /usr/local/tomcat/webapps/dcm-service-biz/
# Expose ports.  
EXPOSE 8865  

ENV VIMDA=172.*.*.*
COPY ./run-dubbo.sh /run-dubbo.sh
RUN chmod 700 /run-dubbo.sh

#define entry point which will be run first when the container starts up
ENTRYPOINT ["/run-dubbo.sh"]
